export const UI_SET_ACTIVE_CATEGORY = 'UI_SET_ACTIVE_CATEGORY';
export const UI_UNSET_ACTIVE_CATEGORY = 'UI_UNSET_ACTIVE_CATEGORY';
export const UI_SET_SEARCH_MODE_ON = 'UI_SET_SEARCH_MODE_ON';
export const UI_SET_SEARCH_MODE_OFF = 'UI_SET_SEARCH_MODE_OFF';
export const UI_SET_SEARCH_QUERY = 'UI_SET_SEARCH_QUERY';
export const UI_SET_FILTER_SHOW_COMPLETED_TASK = 'UI_SET_FILTER_SHOW_COMPLETED_TASK';
export const UI_SET_ACTIVE_TASK = 'UI_SET_ACTIVE_TASK';
export const UI_UNSET_ACTIVE_TASK = 'UI_UNSET_ACTIVE_TASK';