export const CATEGORY_CREATE = 'CATEGORY_CREATE';
export const CATEGORY_UPDATE = 'CATEGORY_UPDATE';
export const CATEGORY_DELETE = 'CATEGORY_DELETE';
export const CATEGORY_SYNC = 'CATEGORY_SYNC';

export const CATEGORY_ADD_TO_SYNC_QUEUE = 'CATEGORY_ADD_TO_SYNC_QUEUE';
export const CATEGORY_CLEAN_SYNC_QUEUE = 'CATEGORY_CLEAN_SYNC_QUEUE';
