export const CATEGORY_ADD = 'CATEGORY_ADD';
export const CATEGORY_EDIT = 'CATEGORY_EDIT';
export const CATEGORY_DELETE = 'CATEGORY_DELETE';
export const CATEGORY_SET_ACTIVE = 'CATEGORY_SET_ACTIVE';
export const CATEGORY_RESET_ACTIVE = 'CATEGORY_RESET_ACTIVE';
