export const CATEGORY_ADD = 'CATEGORY_ADD';
export const CATEGORY_ADD_NESTED = 'CATEGORY_ADD_NESTED';
export const CATEGORY_EDIT = 'CATEGORY_EDIT';
export const CATEGORY_INITIAL_DELETE = 'CATEGORY_INITIAL_DELETE';
export const CATEGORY_DELETE = 'CATEGORY_DELETE';
export const CATEGORY_TITLE_CHANGE = 'CATEGORY_TITLE_CHANGE';
