export const TASK_FILTER_SEARCH_CHANGE = 'TASK_FILTER_SEARCH_CHANGE';
export const TASK_FILTER_SHOW_DONE_CHANGE = 'TASK_FILTER_SHOW_DONE_CHANGE';
export const TASK_FILTER_SEARCH_RESET = 'TASK_FILTER_SEARCH_RESET';