export const NEW_TASK_TITLE_CHANGE = 'NEW_TASK_TITLE_CHANGE';
export const NEW_TASK_ADD = 'NEW_TASK_ADD';
export const TASK_STATUS_TOGGLE = 'TASK_STATUS_TOGGLE';
export const EDIT_TASK_TITLE_CHANGE = 'EDIT_TASK_TITLE_CHANGE';
export const EDIT_TASK_DESCRIPTION_CHANGE = 'EDIT_TASK_DESCRIPTION_CHANGE';
export const EDIT_TASK_STATUS_TOGGLE = 'EDIT_TASK_STATUS_TOGGLE';
export const EDIT_TASK_SAVE = 'EDIT_TASK_SAVE';
export const CATEGORY_DELETE_TASKS = 'CATEGORY_DELETE_TASKS';
export const TASK_FILTER_SEARCH_CHANGE = 'TASK_FILTER_SEARCH_CHANGE';
export const TASK_FILTER_SHOW_DONE_CHANGE = 'TASK_FILTER_SHOW_DONE_CHANGE';
export const TASK_FILTER_SEARCH_RESET = 'TASK_FILTER_SEARCH_RESET';


