export const TASK_DELETE = 'TASK_DELETE';
export const TASK_CREATE = 'TASK_CREATE';
export const TASK_STATUS_CHANGE = 'TASK_STATUS_CHANGE';
export const TASK_TITLE_CHANGE = 'TASK_TITLE_CHANGE';
export const TASK_DESCRIPTION_CHANGE = 'TASK_DESCRIPTION_CHANGE';
export const TASK_CATEGORY_CHANGE = 'TASK_CATEGORY_CHANGE';
